### ISSUE TITLE
Failed to install fasm1 1.73.32 for Windows updated on 2024-08-31 (probably because of a wrong/changed hash)

### ISSUE THREAD

**Issue by insolor** [stevenwdv/setup-fasm#112]
Installation log

```
using 1.73.32
  trying https://flatassembler.net/fasmw17332.zip
  Warning: expected hash 192f6a51d796ea8c93c080636a87f214a56793836f2b4b9f5dcc84f41d24e1c9f5262ae717c1464be8dab3312bd3ddc6c08837dc43086df18df4ed0c94f249fe but got 57634c0d773d320bbd1d0aea8cad1db7ccff50d3ca25d1e966d6f231fb5eb4dad545d408b9f3a32afffdd8cad1ab4137ce62c0d34d314a61fd8c7345358b6971 for https://flatassembler.net/fasmw17332.zip for fasm1 1.73.32 for windows, you may want to report this to the setup-fasm action maintainer; not using this file
  trying http://fasm.sourceforge.net/archive/recent/fasmw17332.zip
  Protocol "https:" not supported. Expected "http:"
  Waiting 10 seconds before trying again
  Protocol "https:" not supported. Expected "http:"
  Waiting 12 seconds before trying again
  Error: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
      at new ClientRequest (node:_http_client:183:11)
      at Object.request (node:https:379:10)
      at e.HttpClient.requestRawWithCallback (D:\a\_actions\stevenwdv\setup-fasm\v1\dist\setup.js:228:55)
      at D:\a\_actions\stevenwdv\setup-fasm\v1\dist\setup.js:226:166
      at new Promise (<anonymous>)
      at e.HttpClient.<anonymous> (D:\a\_actions\stevenwdv\setup-fasm\v1\dist\setup.js:226:140)
      at Generator.next (<anonymous>)
      at D:\a\_actions\stevenwdv\setup-fasm\v1\dist\setup.js:189:108
      at new Promise (<anonymous>)
      at o (D:\a\_actions\stevenwdv\setup-fasm\v1\dist\setup.js:188:67) {
    code: 'ERR_INVALID_PROTOCOL'
  }
```

On the [downloads](https://flatassembler.net/download.php) page it shows that this version for windows was updated on 2024-08-31, but the same version for Linux was updated in December 2023:

![image](https://github.com/user-attachments/assets/10db528b-6716-428f-b8ce-e42a9b82ce79)

It seems, that the zip file for Windows was updated without version number change.

**Comment by stevenwdv** [comment]
Thanks, should be fixed by stevenwdv/fasm-versions#36, the automated workflow to check for updated hashes was disabled automatically.
